spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/enterprisetalentmanagement?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml